
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tapi.tasdid
  resources:
  - tcrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tapi.tasdid
  resources:
  - tcrds/finalizers
  verbs:
  - update
- apiGroups:
  - tapi.tasdid
  resources:
  - tcrds/status
  verbs:
  - get
  - patch
  - update
