# permissions for end users to view tcrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tcrd-viewer-role
rules:
- apiGroups:
  - tapi.tasdid
  resources:
  - tcrds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tapi.tasdid
  resources:
  - tcrds/status
  verbs:
  - get
