# permissions for end users to edit tcrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tcrd-editor-role
rules:
- apiGroups:
  - tapi.tasdid
  resources:
  - tcrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tapi.tasdid
  resources:
  - tcrds/status
  verbs:
  - get
